# Generated by Django 6.1.1 on 2026-09-06 11:32

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('name', models.TextField(blank=True)),
                ('hgnc_id', models.CharField(blank=True, max_length=20)),
                ('entrez_id', models.CharField(blank=True, max_length=20)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='CPM per sample, ordered by Sample.column_index.')),
                ('mean_log2', models.FloatField(db_index=True)),
                ('is_expressed', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'brainvar_gene',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol', 'ensembl_id'], name='brainvar_ge_symbol_56a0ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braincode', models.CharField(db_index=True, max_length=32, unique=True)),
                ('age_days', models.FloatField(help_text='Age in days from conception; birth is ~280.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('age', models.FloatField(help_text='Age in age_units, as reported.')),
                ('age_units', models.CharField(help_text='PCW or Years.', max_length=8)),
                ('period', models.PositiveSmallIntegerField(help_text='Developmental period, 1-12.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('epoch', models.PositiveSmallIntegerField(help_text='Broad developmental stage, 0-3.')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('tissue', models.CharField(default='cortex', max_length=32)),
                ('column_index', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'brainvar_sample',
                'ordering': ['age_days'],
                'indexes': [models.Index(fields=['age_days'], name='brainvar_sa_age_day_db2284_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('cpm', 'CPM matrix'), ('hgnc', 'HGNC mapping'), ('ensembl', 'Ensembl id')], max_length=10)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='brainvar.gene')),
            ],
            options={
                'verbose_name_plural': 'gene aliases',
                'db_table': 'brainvar_gene_alias',
                'indexes': [models.Index(fields=['alias'], name='brainvar_ge_alias_9ebaf1_idx')],
            },
        ),
    ]
