# Generated by Django 6.1.1 on 2026-09-06 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254, verbose_name='actor email')),
                ('action', models.CharField(choices=[('sign_in', 'Signed in'), ('sign_in_failed', 'Failed sign-in'), ('sign_out', 'Signed out'), ('gene_view', 'Viewed gene'), ('export_png', 'Exported PNG'), ('invite_sent', 'Sent invitation')], max_length=32)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access event',
                'verbose_name_plural': 'access events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_recent_idx'), models.Index(fields=['actor', '-timestamp'], name='activity_actor_idx'), models.Index(fields=['action', '-timestamp'], name='activity_action_idx')],
            },
        ),
    ]
