"""
Verify the numpy LOESS against skmisc — the library the original script uses.

The fixtures in reference/ were generated by scripts/make_loess_reference.py
running skmisc itself on four genes, capturing both:

    fitted/lower/upper            skmisc defaults (interpolating kd-tree
                                  surface, approximate statistics)
    fittedExact/lowerExact/...    surface="direct", statistics="exact"

Our implementation reproduces the *exact* solution, which is what these tests
assert. skmisc's default is an approximation of that same solution and drifts
from it by up to ~0.85 log2 units on this data.
"""

import json
from pathlib import Path

import numpy as np
from django.test import SimpleTestCase

from brainvar.loess import Loess, t_cdf, t_quantile

REFERENCE_DIR = Path(__file__).parent / "reference"
GENES = ["SCN2A", "SYNGAP1", "XIST", "MEF2C"]

# Fitted values are a linear functional of y, so they match to machine
# precision. The band additionally depends on sigma and df, where skmisc's
# internal numerics differ slightly.
FIT_TOLERANCE = 1e-6
BAND_TOLERANCE = 2e-3


def load_reference(symbol: str) -> dict:
    with (REFERENCE_DIR / f"{symbol}.json").open() as f:
        return json.load(f)


class LoessAgainstSkmiscTests(SimpleTestCase):
    """The numbers that matter: do we agree with the reference library?"""

    def test_fitted_matches_exact_solution(self):
        for symbol in GENES:
            with self.subTest(gene=symbol):
                ref = load_reference(symbol)
                fitted, _ = Loess(ref["x"], ref["y"]).predict(ref["x"])
                worst = np.max(np.abs(fitted - np.array(ref["fittedExact"])))
                self.assertLess(worst, FIT_TOLERANCE, f"{symbol}: max diff {worst:.3g}")

    def test_confidence_band_matches_exact_solution(self):
        for symbol in GENES:
            with self.subTest(gene=symbol):
                ref = load_reference(symbol)
                band = Loess(ref["x"], ref["y"]).confidence(ref["x"])
                lower = np.max(np.abs(band.lower - np.array(ref["lowerExact"])))
                upper = np.max(np.abs(band.upper - np.array(ref["upperExact"])))
                self.assertLess(lower, BAND_TOLERANCE, f"{symbol}: lower {lower:.3g}")
                self.assertLess(upper, BAND_TOLERANCE, f"{symbol}: upper {upper:.3g}")

    def test_within_skmisc_default_approximation_error(self):
        """
        skmisc's default surface is itself an approximation. We only require
        our exact fit to sit inside the envelope of its own deviation.
        """
        for symbol in GENES:
            with self.subTest(gene=symbol):
                ref = load_reference(symbol)
                fitted, _ = Loess(ref["x"], ref["y"]).predict(ref["x"])
                default = np.array(ref["fitted"])
                exact = np.array(ref["fittedExact"])
                skmisc_own_error = np.max(np.abs(default - exact))
                ours = np.max(np.abs(fitted - default))
                self.assertLessEqual(ours, skmisc_own_error + 1e-9)


class LoessBehaviourTests(SimpleTestCase):
    """Properties that must hold regardless of the reference data."""

    def test_constant_data_fits_a_constant(self):
        x = np.linspace(0, 10, 30)
        fitted, _ = Loess(x, np.full(30, 5.0)).predict(x)
        np.testing.assert_allclose(fitted, 5.0, atol=1e-8)

    def test_quadratic_is_reproduced_exactly(self):
        """Degree 2 local fits recover a global quadratic."""
        x = np.linspace(-3, 3, 40)
        y = 2 * x**2 - 3 * x + 1
        fitted, _ = Loess(x, y).predict(x)
        np.testing.assert_allclose(fitted, y, atol=1e-6)

    def test_unsorted_input_gives_the_same_answer(self):
        rng = np.random.default_rng(0)
        x = rng.uniform(0, 10, 60)
        y = np.sin(x) + rng.normal(0, 0.1, 60)
        shuffled = rng.permutation(60)

        a, _ = Loess(x, y).predict(np.linspace(1, 9, 20))
        b, _ = Loess(x[shuffled], y[shuffled]).predict(np.linspace(1, 9, 20))
        np.testing.assert_allclose(a, b, atol=1e-12)

    def test_confidence_band_brackets_the_fit(self):
        ref = load_reference("SCN2A")
        band = Loess(ref["x"], ref["y"]).confidence(ref["x"])
        self.assertTrue(np.all(band.lower <= band.fitted))
        self.assertTrue(np.all(band.fitted <= band.upper))
        self.assertTrue(np.all(band.se >= 0))

    def test_silent_gene_does_not_blow_up(self):
        """A gene that is zero everywhere fits a flat line at the floor."""
        x = np.log2(np.linspace(43, 7566, 176))
        y = np.full(176, np.log2(0.0 + 1e-3))
        band = Loess(x, y).confidence(x)
        np.testing.assert_allclose(band.fitted, y[0], atol=1e-8)
        self.assertFalse(np.any(np.isnan(band.lower)))

    def test_rejects_too_few_points(self):
        with self.assertRaises(ValueError):
            Loess([1.0, 2.0], [1.0, 2.0])

    def test_rejects_mismatched_lengths(self):
        with self.assertRaises(ValueError):
            Loess([1.0, 2.0, 3.0, 4.0], [1.0, 2.0])


class StudentTTests(SimpleTestCase):
    """The t distribution used for the confidence band."""

    def test_cdf_known_values(self):
        self.assertAlmostEqual(t_cdf(0, 10), 0.5, places=10)
        self.assertAlmostEqual(t_cdf(1.812, 10), 0.95, places=3)
        self.assertAlmostEqual(t_cdf(-1.812, 10), 0.05, places=3)
        self.assertAlmostEqual(t_cdf(1.96, 1e6), 0.975, places=3)

    def test_quantile_inverts_cdf(self):
        for df in (3.0, 7.5, 30.0, 171.3):
            for p in (0.6, 0.75, 0.9, 0.975, 0.99):
                with self.subTest(df=df, p=p):
                    self.assertAlmostEqual(t_cdf(t_quantile(p, df), df), p, places=6)

    def test_quantile_known_value(self):
        self.assertAlmostEqual(t_quantile(0.975, 10), 2.228, places=3)
