"""
LOESS (locally estimated scatterplot smoothing) with pointwise confidence
intervals — a numpy implementation of what `skmisc.loess` computes for the
original per_gene_cpm_brainvar.py (span 0.75, degree 2, gaussian family).

Why not use skmisc directly: it publishes no linux/aarch64 wheels, so it
cannot be installed in a container on Apple Silicon without either x86
emulation or a Fortran toolchain in the image. numpy has wheels everywhere.

Method — at each evaluation point x0, fit a weighted quadratic over the
q = floor(span*n) nearest neighbours with tricube weights, and read off the
smoother vector l(x0) such that fit(x0) = l(x0) . y. Residual variance and
effective degrees of freedom come from the exact smoother matrix L over the
training points:

    sigma^2 = RSS / d1,   d1 = tr[(I-L)'(I-L)],   d2 = tr[((I-L)'(I-L))^2]
    df      = d1^2 / d2

matching Cleveland, Grosse & Shyu's loess inference. skmisc's *default*
evaluates on an interpolating kd-tree surface and approximates d1/d2; this
implementation reproduces its exact solution (surface="direct",
statistics="exact") to within 1e-6. See tests/test_loess.py.

Verified against fixtures generated by skmisc itself — the same reference data
the TypeScript port in frontend/src/lib/loess.ts is tested against.
"""

from dataclasses import dataclass

import numpy as np

# Below this, a determinant or window width counts as degenerate.
TINY = 1e-12


@dataclass(frozen=True)
class LoessBand:
    """A fitted curve with its pointwise confidence band."""

    x: np.ndarray
    fitted: np.ndarray
    se: np.ndarray
    lower: np.ndarray
    upper: np.ndarray


class Loess:
    """
    Local regression over one predictor.

        model = Loess(x, y)                 # fits on construction
        band = model.confidence(x_out)      # curve + 95% band

    `x` need not be sorted and ties are fine. Requires n >= degree + 2.
    """

    def __init__(self, x, y, span: float = 0.75, degree: int = 2):
        x = np.asarray(x, dtype=np.float64)
        y = np.asarray(y, dtype=np.float64)

        if x.shape != y.shape:
            raise ValueError("x and y must have equal length")
        if x.ndim != 1:
            raise ValueError("x and y must be one-dimensional")
        if degree not in (1, 2):
            raise ValueError("degree must be 1 or 2")
        if x.size < degree + 2:
            raise ValueError(f"need at least {degree + 2} points, got {x.size}")

        self.span = float(span)
        self.degree = int(degree)
        self.n = int(x.size)

        # Sort once; every window is then a contiguous neighbourhood.
        order = np.argsort(x, kind="stable")
        self.x = x[order]
        self.y = y[order]

        # Exact smoother matrix L over the training points. Row i is the
        # smoother vector at x_i, so fitted = L @ y.
        L = np.empty((self.n, self.n), dtype=np.float64)
        for i in range(self.n):
            L[i] = self._l_vector(self.x[i])

        self.fitted = L @ self.y
        residuals = self.y - self.fitted
        rss = float(residuals @ residuals)

        # B = (I - L)'(I - L); d1 = tr(B), d2 = tr(B^2) = sum of squares
        # because B is symmetric.
        M = np.eye(self.n) - L
        B = M.T @ M
        d1 = float(np.trace(B))
        d2 = float(np.sum(B * B))

        self.sigma = np.sqrt(max(rss, 0.0) / d1) if d1 > 0 else 0.0
        self.df = (d1 * d1) / d2 if d2 > 0 else max(self.n - 2, 1)

    # -- the core of the method --------------------------------------------

    def _l_vector(self, x0: float) -> np.ndarray:
        """
        Smoother vector l(x0), where fit(x0) = sum_i l_i(x0) * y_i.

        Built by solving the weighted least-squares problem for a local
        polynomial centred on x0, then extracting the row of the hat matrix
        rather than the coefficients — the value at x0 is just the intercept.
        """
        x, n = self.x, self.n

        # Window size: the q nearest neighbours.
        q = int(np.floor(self.span * n))
        q = max(q, self.degree + 1)
        q = min(q, n)

        dist = np.abs(x - x0)
        d = np.partition(dist, q - 1)[q - 1]  # distance to the qth neighbour

        # For span > 1 the C loess widens the window by span^(1/p), p = 1 here.
        if self.span > 1:
            d *= self.span

        if d < TINY:
            # Every neighbour sits on x0: average the exact matches.
            hits = dist < TINY
            l = np.zeros(n)
            l[hits] = 1.0 / np.count_nonzero(hits)
            return l

        # Tricube weights, zero outside the window.
        u = dist / d
        w = np.where(u < 1.0, (1.0 - u**3) ** 3, 0.0)

        dx = x - x0
        inside = w > 0.0

        # Weighted moments of the local basis [1, dx, dx^2].
        if self.degree == 1:
            s0 = np.sum(w)
            s1 = np.sum(w * dx)
            s2 = np.sum(w * dx * dx)
            det = s0 * s2 - s1 * s1
            if abs(det) < TINY:
                return self._weighted_mean(w, s0, inside)
            l = np.zeros(n)
            l[inside] = w[inside] * (s2 - s1 * dx[inside]) / det
            return l

        wd = w * dx
        s0 = np.sum(w)
        s1 = np.sum(wd)
        s2 = np.sum(wd * dx)
        s3 = np.sum(wd * dx * dx)
        s4 = np.sum(wd * dx * dx * dx)

        # Solve the symmetric 3x3 normal equations for the first row of M^-1;
        # only that row is needed, since the fit at x0 is the intercept.
        row = _first_row_inverse_3x3(s0, s1, s2, s3, s4)
        if row is None:
            return self._weighted_mean(w, s0, inside)

        a, b, c = row
        l = np.zeros(n)
        l[inside] = w[inside] * (a + b * dx[inside] + c * dx[inside] ** 2)
        return l

    @staticmethod
    def _weighted_mean(w: np.ndarray, s0: float, inside: np.ndarray) -> np.ndarray:
        """Fallback when the local system is singular (e.g. constant x)."""
        l = np.zeros(w.size)
        if s0 > 0:
            l[inside] = w[inside] / s0
        return l

    # -- prediction ---------------------------------------------------------

    def predict(self, points) -> tuple[np.ndarray, np.ndarray]:
        """Fitted values and standard errors at arbitrary x positions."""
        points = np.atleast_1d(np.asarray(points, dtype=np.float64))
        fitted = np.empty(points.size)
        se = np.empty(points.size)

        for k, x0 in enumerate(points):
            l = self._l_vector(float(x0))
            fitted[k] = l @ self.y
            se[k] = self.sigma * np.sqrt(l @ l)

        return fitted, se

    def confidence(self, points, alpha: float = 0.05) -> LoessBand:
        """
        Pointwise confidence band. Default alpha=0.05 gives the 95% band the
        original script draws.
        """
        points = np.atleast_1d(np.asarray(points, dtype=np.float64))
        fitted, se = self.predict(points)
        t = t_quantile(1.0 - alpha / 2.0, self.df)
        return LoessBand(
            x=points,
            fitted=fitted,
            se=se,
            lower=fitted - t * se,
            upper=fitted + t * se,
        )


def _first_row_inverse_3x3(s0, s1, s2, s3, s4):
    """
    First row of the inverse of the symmetric matrix

        [[s0, s1, s2],
         [s1, s2, s3],
         [s2, s3, s4]]

    Returns None when it is singular.
    """
    A = s2 * s4 - s3 * s3
    B = s2 * s3 - s1 * s4
    C = s1 * s3 - s2 * s2
    det = s0 * A + s1 * B + s2 * C
    if abs(det) < TINY:
        return None
    return A / det, B / det, C / det


# -- Student's t --------------------------------------------------------------
# The band needs a t quantile at a non-integer df. Implemented here rather than
# pulling in scipy, which would add ~90 MB to the image for one function.


def t_cdf(t: float, df: float) -> float:
    """CDF of Student's t distribution."""
    from math import lgamma

    x = df / (df + t * t)
    ib = _beta_incomplete(df / 2.0, 0.5, x, lgamma)
    return 1.0 - ib / 2.0 if t >= 0 else ib / 2.0


def t_quantile(p: float, df: float) -> float:
    """Quantile of Student's t, by bisection on the CDF."""
    if not df > 0:
        return float("nan")
    if p == 0.5:
        return 0.0

    sign = 1.0 if p > 0.5 else -1.0
    target = p if p > 0.5 else 1.0 - p

    lo, hi = 0.0, 1.0
    while t_cdf(hi, df) < target and hi < 1e6:
        hi *= 2.0
    for _ in range(200):
        mid = (lo + hi) / 2.0
        if t_cdf(mid, df) < target:
            lo = mid
        else:
            hi = mid
        if hi - lo < 1e-10:
            break
    return sign * (lo + hi) / 2.0


def _beta_incomplete(a: float, b: float, x: float, lgamma) -> float:
    """Regularised incomplete beta I_x(a, b), by Lentz's continued fraction."""
    import math

    if x <= 0:
        return 0.0
    if x >= 1:
        return 1.0

    lbeta = lgamma(a) + lgamma(b) - lgamma(a + b)
    symmetric = x >= (a + 1) / (a + b + 2)
    aa, bb, xx = (b, a, 1 - x) if symmetric else (a, b, x)

    front = math.exp(aa * math.log(xx) + bb * math.log(1 - xx) - lbeta)

    c = 1.0
    d = 1.0 - ((aa + bb) * xx) / (aa + 1.0)
    if abs(d) < 1e-30:
        d = 1e-30
    d = 1.0 / d
    h = d

    for m in range(1, 301):
        m2 = 2 * m
        num = (m * (bb - m) * xx) / ((aa + m2 - 1) * (aa + m2))
        d = 1.0 + num * d
        if abs(d) < 1e-30:
            d = 1e-30
        c = 1.0 + num / c
        if abs(c) < 1e-30:
            c = 1e-30
        d = 1.0 / d
        h *= d * c

        num = -((aa + m) * (aa + bb + m) * xx) / ((aa + m2) * (aa + m2 + 1))
        d = 1.0 + num * d
        if abs(d) < 1e-30:
            d = 1e-30
        c = 1.0 + num / c
        if abs(c) < 1e-30:
            c = 1e-30
        d = 1.0 / d
        delta = d * c
        h *= delta
        if abs(delta - 1.0) < 1e-12:
            break

    value = front * h / aa
    return 1.0 - value if symmetric else value
