# Generated by Django 6.1.1 on 2026-09-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin_group_write_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='When the welcome email was last sent. Null if never invited.', null=True, verbose_name='invitation sent'),
        ),
    ]
