# Generated by Django 6.1.1 on 2026-09-06 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_invited_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': [('view_audit_logs', 'Can view the audit log')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
